name: Do It!

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
      - ready_for_review

jobs:
  do-it-now:
    uses: NaturalArtMedia/.github/.github/workflows/draft-release.yml@main
